### ISSUE TITLE
qpter not opening on Debian Linux

### ISSUE THREAD

**Issue by jason-mehmel** [vonshednob/pter#31]
Trying to run qpter from the system doesn't work!

Running it from the command line got this response:

```
Traceback (most recent call last):
  File "/home/jason/.local/bin/qpter", line 8, in <module>
    sys.exit(run())
  File "/home/jason/.local/lib/python3.9/site-packages/pter/main.py", line 127, in run
    run_qtui(args, config)
  File "/home/jason/.local/lib/python3.9/site-packages/pter/qtui.py", line 1817, in run_qtui
    p = Program(config, utils.open_sources(args), fullpath)
TypeError: open_sources() missing 1 required positional argument: 'config'

```

Running Debian Linux: BunsenLabs GNU/Linux 11 (Beryllium)

I've tried updating pter through pip, this was the response: 

```
Requirement already satisfied: pter in ./.local/lib/python3.9/site-packages (3.10.1)
WARNING: Keyring is skipped due to an exception: Failed to unlock the keyring!
Collecting pter
  Using cached pter-3.10.1-py3-none-any.whl (101 kB)
  Using cached pter-3.10.0-py3-none-any.whl (101 kB)
Requirement already satisfied: cursedspace>=1.3.1 in ./.local/lib/python3.9/site-packages (from pter) (1.5.2)
Requirement already satisfied: pytodotxt>=1.1.0 in ./.local/lib/python3.9/site-packages (from pter) (1.4.3)
```

(Warning only there because of the KDE wallet, but hasn't been a problem using this system before.)

So I think I'm up to date!

**Comment by vonshednob** [comment]
Eek! Thanks for pointing it out, I haven’t started qpter in ages myself. I’ll fix it asap!

**Comment by vonshednob** [comment]
Alright, 3.11.0 should solve this! Can you confirm?

**Comment by jason-mehmel** [comment]
Confirmed! Working as expected.
